name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v1
      with:
        name: linux
        path: target/release/ares
  build-mac:
    name: Build Mac
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v1
      with:
        name: mac
        path: target/release/ares