name: tests-build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v1
      with:
        name: linux
        path: target/release/ares
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v1
      with:
        name: mac
        path: target/release/ares
